# Generated by Django 5.0.6 on 2024-06-16 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('person', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
